module.exports = {
  extends: ['airbnb', 'airbnb/hooks'],
  rules: {
    'no-use-before-define': 'off',
    'no-undef': 'off',
    'consistent-return': 'off',
    'import/no-unresolved': 'off',
    'import/extensions': 'off',
    'import/prefer-default-export': 'off',
    'prefer-regex-literals': 'off',
    'react/react-in-jsx-scope': 'off',
    'react/prop-types':'off',
    'react/function-component-definition': 'off',
    'react/jsx-props-no-spreading': 'off',
    'react/require-default-props': 'off',
    'react/jsx-filename-extension': [
      2,
      { extensions: ['.js', '.jsx', '.ts', '.tsx'] },
    ],
    'jsx-a11y/click-events-have-key-events': 'off',
    'jsx-a11y/no-static-element-interactions': 'off',
    'jsx-a11y/no-noninteractive-element-interactions': 'off',
    'jsx-a11y/anchor-is-valid': 'off',
  },
};
