# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
    - master

jobs:
  bump-version-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "hot9998@naver.com"
      - run: git config --global user.name "ChangHyun Kim"
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/upload-artifact@v2
        with:
          name: src
          path: ./
      - run: npm version patch
      - run: git push origin master --tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

